apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: qj41eigxj-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-c51a233f56.7p73.p3.openshiftapps.com/rhtap/rhtap-qe:349734fe26e3ada45aa6d18cc2a5254641d50267@sha256:5751e742ab5c8e5e1236549a3b69e1037c8f6e260b455f9c34eea3c59c999709
          name: container-image
